### ISSUE TITLE
Error in types.hs

### ISSUE THREAD

**Issue by flip111** [Peaker/lamdu#27] opened 2015-01-24 08:26 UTC
while doing `cabal install`

```
Lamdu/Sugar/Types.hs:491:1:
    The second argument of ‘Scope’ should have kind ‘* -> *’,
      but ‘m_1628154838’ has kind ‘*’
    In the instance declaration for
      ‘Monoid (Scope name_1628154837 m_1628154838)’
cabal: Error: some packages failed to install:
lamdu-0.1 failed during the building phase. The exception was:
ExitFailure 1
```

ghc 7.8.3 by installing haskell platform 2014.2.0.0

**Comment by temoto** [comment] 2015-01-24 14:57
Also fails on GHC 7.8.4:
```
Lamdu/Sugar/Types/Internal.hs:43:24: Warning:
    In the use of type constructor or class ‘Typeable1’
    (imported from Data.Typeable, but defined in Data.Typeable.Internal):
    Deprecated: "renamed to 'Typeable'"
[18 of 77] Compiling Lamdu.Sugar.Types ( Lamdu/Sugar/Types.hs, dist/dist-sandbox-7230062d/build/lamdu/lamdu-tmp/Lamdu/Sugar/Types.o )

Lamdu/Sugar/Types.hs:491:1:
    The second argument of ‘Scope’ should have kind ‘* -> *’,
      but ‘m_1628154822’ has kind ‘*’
    In the instance declaration for
      ‘Monoid (Scope name_1628154821 m_1628154822)’
```

**Comment by temoto** [comment] 2015-01-24 16:25
Also fails on GHC 7.4.1 (stock in Ubuntu 12.04):
```
Lamdu/Sugar/Types.hs:491:1:
    Kind mis-match
    The second argument of `Scope' should have kind `* -> *',
    but `m_1627725804' has kind `*'
    In the instance declaration for `Monoid (Scope name_1627725803 m_1627725804)'
```

Which version do developers use?

**Comment by temoto** [comment] 2015-01-24 17:23
Stick poking method revealed that the problem is in `derive 2.5.19` dependency. Pull request incoming.

**Comment by Peaker** [comment] 2015-01-24 17:35
Thanks for the support, we appreciate your intentions but the current
branch is wip_integration which iirc doesn't depend on derive.

Will be merged to master soon...

**Comment by flip111** [comment] 2015-01-24 20:43
Maybe a bit redundant by now but i also test with GHC 7.6.3 and same error on there.

@Peaker are you saying that the wip_integration branch is the one new users should use? In the tutorial there is no mention of downloading lamdu so i assumed git clone the master branch before doing the [cabal install](https://github.com/Peaker/lamdu/blob/master/TUTORIAL#L15)

**Comment by flip111** [comment] 2015-01-24 22:16
On the `wip_integration` branch

```
» cabal install
Resolving dependencies...
Configuring lamdu-ide-0.1...
Building lamdu-ide-0.1...
Failed to install lamdu-ide-0.1
Build log ( /home/flip111/.cabal/logs/lamdu-ide-0.1.log ):
Configuring lamdu-ide-0.1...
Building lamdu-ide-0.1...
Preprocessing library lamdu-ide-0.1...
setup-Simple-Cabal-1.22.0.0-x86_64-linux-ghc-7.8.3: can't find source for
Data/Map/Utils in bottlelib, submodules/AlgoW, dist/build/autogen
cabal: Error: some packages failed to install:
lamdu-ide-0.1 failed during the building phase. The exception was:
ExitFailure 1

**Comment by Peaker** [comment] 2015-01-25 04:37
There's a submodule there, you need to git submodule update --init

**Comment by Peaker** [comment] 2015-06-18 18:50
wip_integration has been merged to master, master should work now (though it requires a fork of graphics-drawingcombinators at the moment)

**Closed by Peaker** 2015-06-18 18:50 UTC
